spring:
  application:
    name: gateway
  profiles:
    active: dev

management:
  endpoints:
    web:
      exposure:
        include: "*"
  # enabled-by-default: false
  #tracing:
  #  sampling:
  #    probability: 1.0
  #  propagation:
  #    type: b3

#logging:
#  pattern:
#    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'

server:
  port: 8222
